version: "3.9"

services:
  fe:
    container_name: quiztekFrontend
    build: ./quiztekfe
    depends_on:
      - be
    ports:
      - "3000:3000"
    env_file:
      - ./quiztekfe/.env

  be:
    container_name: quiztekBackend
    build: ./quiztekbe
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./quiztekbe/.env

  db:
    container_name: quiztekDatabase
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./quiztekbe/init.sql:/docker-entrypoint-initdb.d/init.sql