basePath: /
definitions:
  main.Question:
    properties:
      answer_tf:
        type: boolean
      choices:
        items:
          type: string
        type: array
      correct_answers:
        items:
          type: string
        type: array
      correct_choice:
        type: integer
      message:
        type: string
      position:
        type: integer
      question_id:
        type: string
      quiz_id:
        type: string
      type:
        description: '''tf'', ''mc'', ''fib'''
        type: string
    type: object
  main.Question_Update:
    properties:
      answer_tf:
        type: boolean
      choices:
        items:
          type: string
        type: array
      correct_answers:
        items:
          type: string
        type: array
      correct_choice:
        type: integer
      message:
        type: string
      type:
        type: string
    type: object
  main.Quiz:
    properties:
      category:
        type: string
      created_at:
        type: string
      creator_email:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  main.Quiz_Detail:
    properties:
      category:
        type: string
      created_at:
        type: string
      creator_email:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  main.Quiz_Post:
    properties:
      category:
        type: string
      title:
        type: string
    type: object
  main.Quiz_Update:
    properties:
      category:
        type: string
      title:
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: Backend for Quiztek
  title: quiztekbe
  version: "1.0"
paths:
  /question/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a question by its ID, then update the positions of subsequent
        questions in the same quiz.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Status message indicating deletion
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid question ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Question not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error during deletion or position update
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a question
      tags:
      - question
    get:
      consumes:
      - application/json
      description: Retrieve the details of a question by its ID.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Question'
        "400":
          description: Invalid question ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Question not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a single question
      tags:
      - question
    patch:
      consumes:
      - application/json
      description: Update specific fields of an existing question by its ID. The quiz_id
        remains unchanged.
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      - description: Fields to update for the question
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.Question_Update'
      produces:
      - application/json
      responses:
        "200":
          description: Success status message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid question ID or JSON payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to update question
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a question
      tags:
      - question
  /quiz:
    get:
      consumes:
      - application/json
      description: Get all quizzes from the database, optionally filtering by title,
        category, or date.
      parameters:
      - description: Quiz title to search for
        in: query
        name: title
        type: string
      - description: Quiz category to search for
        in: query
        name: category
        type: string
      - description: Quiz creation date to search for
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Quiz'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all quizzes
      tags:
      - quiz
    post:
      consumes:
      - application/json
      description: Create a new quiz with the provided title and category.
      parameters:
      - description: Quiz to create
        in: body
        name: quiz
        required: true
        schema:
          $ref: '#/definitions/main.Quiz_Post'
      produces:
      - application/json
      responses:
        "201":
          description: Quiz added message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new quiz
      tags:
      - quiz
  /quiz/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing quiz by its ID.
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Quiz deleted message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request or invalid quiz ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a quiz
      tags:
      - quiz
    get:
      consumes:
      - application/json
      description: Retrieve the details of a quiz by its ID.
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Quiz_Detail'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get a single quiz
      tags:
      - quiz
    patch:
      consumes:
      - application/json
      description: Update the title and category of an existing quiz.
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      - description: Quiz update data
        in: body
        name: quiz
        required: true
        schema:
          $ref: '#/definitions/main.Quiz_Update'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Quiz_Update'
        "400":
          description: Bad request or invalid quiz ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a quiz
      tags:
      - quiz
  /quiz/{id}/question:
    post:
      consumes:
      - application/json
      description: Add a new question at the end of the question list for a specified
        quiz. The position is set as the current count of questions for the quiz plus
        one.
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: New question details including question_id and position
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid quiz ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error getting question count or inserting new question
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new question to a quiz
      tags:
      - quiz
      - question
  /quiz/question/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve an ordered list of question IDs for a specific quiz.
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Invalid quiz id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error fetching questions
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get question IDs for a quiz
      tags:
      - quiz
      - question
swagger: "2.0"
